version: "3"
services:
  airportal:
    depends_on:
      - mongo
      - redis
    container_name: casket
    image: casket
    volumes:
      - ./volumes/casket_volume:/usr/casket_volume
    restart: always
    build: .
    ports:
      - 8070:80
      - 8071:443
    links:
      - mongo
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      port: 8000
      webmaster: "true"
      autobackup: "false"
      host: "http://localhost:8070"
      mongodb: "mongodb://root:example@mongo:27017/casket?authSource=admin"
      lang: "en, no"
      redis: "redis://redis:6379"
      NODE_ENV: "production"
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./volumes/mongo_volume:/data/db
    restart: always
    ports:
      - 8072:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    volumes:
      - ./volumes/redis_volume:/data